export const GEMINI_TTS_VOICES = [
  'Achernar',
  'Achird',
  'Algenib',
  'Algieba',
  'Alnilam',
  'Aoede',
  'Autonoe',
  'Callirrhoe',
  'Charon',
  'Despina',
  'Enceladus',
  'Erinome',
  'Fenrir',
  'Gacrux',
  'Iapetus',
  'Kore',
  'Laomedeia',
  'Leda',
  'Orus',
  'Pulcherrima',
  'Puck',
  'Rasalgethi',
  'Sadachbia',
  'Sadaltager',
  'Schedar',
  'Sulafat',
  'Umbriel',
  'Vindemiatrix',
  'Zephyr',
  'Zubenelgenubi',
];

export const GEMINI_TTS_LANGUAGES = [
  'Arabic (Egypt)',
  'Bangla (Bangladesh)',
  'Dutch (Netherlands)',
  'English (India)',
  'English (US)',
  'French (France)',
  'German (Germany)',
  'Hindi (India)',
  'Indonesian (Indonesia)',
  'Italian (Italy)',
  'Japanese (Japan)',
  'Korean (South Korea)',
  'Marathi (India)',
  'Polish (Poland)',
  'Portuguese (Brazil)',
  'Romanian (Romania)',
  'Russian (Russia)',
  'Spanish (Spain)',
  'Tamil (India)',
  'Telugu (India)',
  'Thai (Thailand)',
  'Turkish (Turkey)',
  'Ukrainian (Ukraine)',
  'Vietnamese (Vietnam)',
  'Afrikaans (South Africa)',
  'Albanian (Albania)',
  'Amharic (Ethiopia)',
  'Arabic (World)',
  'Armenian (Armenia)',
  'Azerbaijani (Azerbaijan)',
  'Basque (Spain)',
  'Belarusian (Belarus)',
  'Bulgarian (Bulgaria)',
  'Burmese (Myanmar)',
  'Catalan (Spain)',
  'Cebuano (Philippines)',
  'Chinese Mandarin (China)',
  'Chinese Mandarin (Taiwan)',
  'Croatian (Croatia)',
  'Czech (Czech Republic)',
  'Danish (Denmark)',
  'English (Australia)',
  'English (UK)',
  'Estonian (Estonia)',
  'Filipino (Philippines)',
  'Finnish (Finland)',
  'French (Canada)',
  'Galician (Spain)',
  'Georgian (Georgia)',
  'Greek (Greece)',
  'Gujarati (India)',
  'Haitian Creole (Haiti)',
  'Hebrew (Israel)',
  'Hungarian (Hungary)',
  'Icelandic (Iceland)',
  'Javanese (Java)',
  'Kannada (India)',
  'Konkani (India)',
  'Lao (Laos)',
  'Latin (Vatican City)',
  'Latvian (Latvia)',
  'Lithuanian (Lithuania)',
  'Luxembourgish (Luxembourg)',
  'Macedonian (North Macedonia)',
  'Maithili (India)',
  'Malagasy (Madagascar)',
  'Malay (Malaysia)',
  'Malayalam (India)',
  'Mongolian (Mongolia)',
  'Nepali (Nepal)',
  'Norwegian Bokmal (Norway)',
  'Norwegian Nynorsk (Norway)',
  'Odia (India)',
  'Pashto (Afghanistan)',
  'Persian (Iran)',
  'Portuguese (Portugal)',
  'Punjabi (India)',
  'Serbian (Serbia)',
  'Sindhi (India)',
  'Sinhala (Sri Lanka)',
  'Slovak (Slovakia)',
  'Slovenian (Slovenia)',
  'Spanish (Latin America)',
  'Spanish (Mexico)',
  'Swahili (Kenya)',
  'Swedish (Sweden)',
  'Urdu (Pakistan)',
];

export const STORYBOARD_ENABLED_LANGUAGES = [
  'English (India)',
  'Hindi (India)',
  'Marathi (India)',
  'Tamil (India)',
  'Telugu (India)',
  'Bangla (Bangladesh)',
  'Gujarati (India)',
  'Kannada (India)',
  'Malayalam (India)',
  'Punjabi (India)',
  'Urdu (Pakistan)',
  'English (US)',
];

export const RECOMMENDED_VOICES = ['Kore', 'Aoede', 'Leda', 'Orus', 'Schedar', 'Vindemiatrix'];

export const LANGUAGE_LITERAL_MAP: Record<string, string> = {
  en: 'English (India)',
  english: 'English (India)',
  hi: 'Hindi (India)',
  hindi: 'Hindi (India)',
  hinglish: 'Hindi (India)',
  bn: 'Bangla (Bangladesh)',
  bangla: 'Bangla (Bangladesh)',
  mr: 'Marathi (India)',
  marathi: 'Marathi (India)',
  ta: 'Tamil (India)',
  tamil: 'Tamil (India)',
  te: 'Telugu (India)',
  telugu: 'Telugu (India)',
  'en-in': 'English (India)',
  'hi-in': 'Hindi (India)',
  'mr-in': 'Marathi (India)',
  'ta-in': 'Tamil (India)',
  'te-in': 'Telugu (India)',
  'gu-in': 'Gujarati (India)',
  'kn-in': 'Kannada (India)',
  'ml-in': 'Malayalam (India)',
  'pa-in': 'Punjabi (India)',
  'ur-pk': 'Urdu (Pakistan)',
  'en-us': 'English (US)',
};

const RECOMMENDED_VOICES_BY_LANGUAGE: Record<string, string[]> = {
  'English (India)': ['Kore', 'Aoede', 'Leda', 'Orus', 'Schedar', 'Vindemiatrix'],
  'Hindi (India)': ['Aoede', 'Kore', 'Leda', 'Orus', 'Schedar', 'Zephyr'],
  'Bangla (Bangladesh)': ['Kore', 'Aoede', 'Leda', 'Orus'],
  'Marathi (India)': ['Kore', 'Aoede', 'Leda', 'Orus'],
  'Tamil (India)': ['Kore', 'Aoede', 'Leda', 'Orus'],
  'Telugu (India)': ['Kore', 'Aoede', 'Leda', 'Orus'],
};

export function resolveStoryboardVoiceLanguage(languageCode: string | null | undefined): string {
  const key = String(languageCode || '').trim().toLowerCase();
  if (!key) return 'English (India)';
  const resolved = LANGUAGE_LITERAL_MAP[key] || 'English (India)';
  return STORYBOARD_ENABLED_LANGUAGES.includes(resolved) ? resolved : 'English (India)';
}

export function getVoicesForLanguage(languageLiteral: string): string[] {
  const recommended = RECOMMENDED_VOICES_BY_LANGUAGE[languageLiteral] || RECOMMENDED_VOICES;
  const rest = GEMINI_TTS_VOICES.filter((voice) => !recommended.includes(voice));
  return [...recommended, ...rest];
}

export const PREVIEW_TEXT_BY_LANGUAGE: Record<string, string> = {
  'English (India)': 'This is a short preview of your ad voice.',
  'Hindi (India)': 'यह आपकी विज्ञापन आवाज़ का छोटा सा प्रीव्यू है।',
  'Marathi (India)': 'हा तुमच्या जाहिरातीच्या आवाजाचा छोटासा प्रीव्यू आहे.',
  'Tamil (India)': 'இது உங்கள் விளம்பர குரலின் சிறிய முன்னோட்டம்.',
  'Telugu (India)': 'ఇది మీ ప్రకటన వాయిస్‌కు చిన్న ప్రివ్యూ.',
  'Bangla (Bangladesh)': 'এটি আপনার বিজ্ঞাপনের কণ্ঠের একটি ছোট প্রিভিউ।',
  'Gujarati (India)': 'આ તમારી જાહેરાતના અવાજનો નાનો પ્રીવ્યુ છે.',
  'Kannada (India)': 'ಇದು ನಿಮ್ಮ ಜಾಹೀರಾತಿನ ಧ್ವನಿಯ ಚಿಕ್ಕ ಪೂರ್ವಾವಲೋಕನ.',
  'Malayalam (India)': 'ഇത് നിങ്ങളുടെ പരസ്യ ശബ്ദത്തിന്റെ ചെറിയൊരു പ്രിവ്യൂ ആണ്।',
  'Punjabi (India)': 'ਇਹ ਤੁਹਾਡੀ ਵਿਗਿਆਪਨ ਆਵਾਜ਼ ਦਾ ਇੱਕ ਛੋਟਾ ਜਿਹਾ ਪ੍ਰੀਵਿਊ ਹੈ।',
  'Urdu (Pakistan)': 'یہ آپ کی اشتہاری آواز کا ایک مختصر پیش نظارہ ہے۔',
  'English (US)': 'This is a short preview of your ad voice.',
};
