services:
  - type: web
    name: rangmanch-api
    env: python
    plan: free
    region: singapore
    rootDir: apps/api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    runtime: python
    pythonVersion: 3.12.7