'use client';

/**
 * TOW Stage 1 — Brand Brief
 *
 * Captures structured input from the user:
 *   brand_name, product_name, target_audience, problem_being_solved,
 *   desired_outcome, call_to_action, trust_points, must_include, must_avoid
 *
 * This is NOT generated by AI — it is user input.
 * When approved, it triggers Project State Pack generation (Stage 2).
 */

import React, { useState } from 'react';
import { StoryboardProject, BriefData } from '../hooks/useStoryboardProject';

interface BriefCheckpointProps {
  project: StoryboardProject;
  onApprove: (brief: BriefData) => Promise<void> | void;
}

function tagsToArray(raw: string): string[] {
  return raw
    .split(/[,\n]/)
    .map((s) => s.trim())
    .filter(Boolean);
}

function arrayToTags(arr: string[]): string {
  return arr.join(', ');
}

export default function BriefCheckpoint({ project, onApprove }: BriefCheckpointProps) {
  // Pre-fill from project data where possible
  const [brandName, setBrandName] = useState(project.brief_data?.brand_name ?? '');
  const [productName, setProductName] = useState(
    project.brief_data?.product_name ?? project.business_brief?.split(' ').slice(0, 5).join(' ') ?? ''
  );
  const [targetAudience, setTargetAudience] = useState(project.brief_data?.target_audience ?? '');
  const [problem, setProblem] = useState(project.brief_data?.problem_being_solved ?? '');
  const [desiredOutcome, setDesiredOutcome] = useState(project.brief_data?.desired_outcome ?? '');
  const [cta, setCta] = useState(project.brief_data?.call_to_action ?? '');
  const [trustPoints, setTrustPoints] = useState(
    arrayToTags(project.brief_data?.trust_points ?? [])
  );
  const [mustInclude, setMustInclude] = useState(
    arrayToTags(project.brief_data?.must_include ?? [])
  );
  const [mustAvoid, setMustAvoid] = useState(
    arrayToTags(project.brief_data?.must_avoid ?? [])
  );

  const [isApproving, setIsApproving] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const validate = (): boolean => {
    const e: Record<string, string> = {};
    if (!brandName.trim()) e.brandName = 'Brand name is required';
    if (!productName.trim()) e.productName = 'Product name is required';
    if (!targetAudience.trim()) e.targetAudience = 'Target audience is required';
    if (!problem.trim()) e.problem = 'Problem being solved is required';
    if (!desiredOutcome.trim()) e.desiredOutcome = 'Desired outcome is required';
    if (!cta.trim()) e.cta = 'Call-to-action is required';
    setErrors(e);
    return Object.keys(e).length === 0;
  };

  const handleApprove = async () => {
    if (!validate()) return;
    setIsApproving(true);
    try {
      const brief: BriefData = {
        brand_name: brandName.trim(),
        product_name: productName.trim(),
        target_audience: targetAudience.trim(),
        problem_being_solved: problem.trim(),
        desired_outcome: desiredOutcome.trim(),
        call_to_action: cta.trim(),
        trust_points: tagsToArray(trustPoints),
        must_include: tagsToArray(mustInclude),
        must_avoid: tagsToArray(mustAvoid),
      };
      await onApprove(brief);
    } finally {
      setIsApproving(false);
    }
  };

  const completedFields = [
    brandName, productName, targetAudience, problem, desiredOutcome, cta,
  ].filter(Boolean).length;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-white rounded-2xl shadow-lg border border-gray-200 p-8">
        <span className="text-xs font-semibold uppercase tracking-widest text-blue-600 bg-blue-50 px-3 py-1 rounded-full">
          TOW · Stage 1 of 13
        </span>
        <h2 className="text-2xl font-bold text-gray-900 mt-3">📋 Brand Brief</h2>
        <p className="text-gray-500 mt-1">
          Provide structured information about your brand and campaign. This brief
          feeds every subsequent AI generation stage — be specific.
        </p>

        {/* Progress bar */}
        <div className="mt-5">
          <div className="flex justify-between text-xs text-gray-400 mb-1">
            <span>{completedFields} / 6 required fields complete</span>
            <span>{Math.round((completedFields / 6) * 100)}%</span>
          </div>
          <div className="w-full bg-gray-100 rounded-full h-1.5">
            <div
              className="bg-blue-500 h-1.5 rounded-full transition-all"
              style={{ width: `${(completedFields / 6) * 100}%` }}
            />
          </div>
        </div>
      </div>

      {/* Form */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Brand & Product */}
        <div className="bg-white rounded-xl border border-gray-200 p-6 space-y-4">
          <h3 className="font-semibold text-gray-800">🏷️ Brand & Product</h3>

          <Field label="Brand Name *" error={errors.brandName}>
            <input
              type="text"
              value={brandName}
              onChange={(e) => setBrandName(e.target.value)}
              placeholder="e.g. GlowSkin India"
              className={fieldCls(errors.brandName)}
            />
          </Field>

          <Field label="Product Name *" error={errors.productName}>
            <input
              type="text"
              value={productName}
              onChange={(e) => setProductName(e.target.value)}
              placeholder="e.g. Vitamin C Brightening Serum"
              className={fieldCls(errors.productName)}
            />
          </Field>
        </div>

        {/* Audience & Problem */}
        <div className="bg-white rounded-xl border border-gray-200 p-6 space-y-4">
          <h3 className="font-semibold text-gray-800">🎯 Audience & Problem</h3>

          <Field label="Target Audience *" error={errors.targetAudience}>
            <input
              type="text"
              value={targetAudience}
              onChange={(e) => setTargetAudience(e.target.value)}
              placeholder="e.g. Women 22–35, urban India, skincare-conscious"
              className={fieldCls(errors.targetAudience)}
            />
          </Field>

          <Field label="Problem Being Solved *" error={errors.problem}>
            <textarea
              value={problem}
              onChange={(e) => setProblem(e.target.value)}
              placeholder="e.g. Dull, uneven skin tone caused by pollution and sun exposure"
              className={fieldCls(errors.problem) + ' resize-none'}
              rows={3}
            />
          </Field>
        </div>

        {/* Outcome & CTA */}
        <div className="bg-white rounded-xl border border-gray-200 p-6 space-y-4">
          <h3 className="font-semibold text-gray-800">✨ Outcome & CTA</h3>

          <Field label="Desired Outcome *" error={errors.desiredOutcome}>
            <textarea
              value={desiredOutcome}
              onChange={(e) => setDesiredOutcome(e.target.value)}
              placeholder="e.g. Viewer feels inspired to try the serum and clicks to shop"
              className={fieldCls(errors.desiredOutcome) + ' resize-none'}
              rows={3}
            />
          </Field>

          <Field label="Call to Action *" error={errors.cta}>
            <input
              type="text"
              value={cta}
              onChange={(e) => setCta(e.target.value)}
              placeholder="e.g. Shop Now — 20% off today only"
              className={fieldCls(errors.cta)}
            />
          </Field>
        </div>

        {/* Trust, Must Include, Must Avoid */}
        <div className="bg-white rounded-xl border border-gray-200 p-6 space-y-4">
          <h3 className="font-semibold text-gray-800">🛡️ Brand Safety & Proof</h3>

          <Field
            label="Trust Points"
            hint="Social proof, stats, certifications — comma-separated"
          >
            <textarea
              value={trustPoints}
              onChange={(e) => setTrustPoints(e.target.value)}
              placeholder="e.g. 50,000 happy customers, Dermatologist tested, 4.8★ on Amazon"
              className={fieldCls() + ' resize-none'}
              rows={2}
            />
          </Field>

          <Field
            label="Must Include"
            hint="Non-negotiable elements — comma-separated"
          >
            <textarea
              value={mustInclude}
              onChange={(e) => setMustInclude(e.target.value)}
              placeholder="e.g. Show bottle label, mention ₹799 price, show 7-day transformation"
              className={fieldCls() + ' resize-none'}
              rows={2}
            />
          </Field>

          <Field
            label="Must Avoid"
            hint="Brand safety rules — comma-separated"
          >
            <textarea
              value={mustAvoid}
              onChange={(e) => setMustAvoid(e.target.value)}
              placeholder="e.g. No competitor names, no medical claims, no before/after skin comparisons"
              className={fieldCls() + ' resize-none'}
              rows={2}
            />
          </Field>
        </div>
      </div>

      {/* Brief Summary Preview */}
      {brandName && productName && targetAudience && (
        <div className="bg-blue-50 border border-blue-200 rounded-xl p-5">
          <p className="text-sm font-semibold text-blue-800 mb-2">📄 Brief Preview</p>
          <p className="text-sm text-blue-700">
            <span className="font-medium">{brandName}</span>'s{' '}
            <span className="font-medium">{productName}</span> — for{' '}
            <span className="font-medium">{targetAudience}</span>
            {problem && ` who struggle with ${problem.toLowerCase()}`}.
            {desiredOutcome && ` Goal: ${desiredOutcome}`}
            {cta && ` CTA: "${cta}"`}
          </p>
        </div>
      )}

      {/* Action Bar */}
      <div className="bg-white rounded-2xl shadow-lg border border-gray-200 p-6 flex items-center gap-4">
        <div className="flex-1">
          <p className="text-sm text-gray-500">
            After approval, AI generates your <strong>Project State Pack</strong> — the memory
            file that guides all subsequent stages.
          </p>
        </div>
        <button
          onClick={handleApprove}
          disabled={isApproving}
          className="px-8 py-3 bg-blue-600 text-white rounded-xl hover:bg-blue-700 font-semibold transition-colors disabled:opacity-50 flex items-center gap-2"
        >
          {isApproving ? (
            <>
              <span className="inline-block animate-spin rounded-full h-4 w-4 border-b-2 border-white" />
              Saving Brief…
            </>
          ) : (
            '✅ Approve Brief & Generate PSP'
          )}
        </button>
      </div>
    </div>
  );
}

// ── Field helper ─────────────────────────────────────────────────────────────

function fieldCls(error?: string): string {
  return [
    'w-full border rounded-lg px-3 py-2 text-sm focus:outline-none transition-colors',
    error
      ? 'border-red-400 focus:border-red-500 bg-red-50'
      : 'border-gray-200 focus:border-blue-400',
  ].join(' ');
}

function Field({
  label,
  hint,
  error,
  children,
}: {
  label: string;
  hint?: string;
  error?: string;
  children: React.ReactNode;
}) {
  return (
    <div>
      <label className="block text-xs font-semibold text-gray-600 mb-1">
        {label}
        {hint && <span className="font-normal text-gray-400 ml-1">— {hint}</span>}
      </label>
      {children}
      {error && <p className="text-xs text-red-500 mt-1">{error}</p>}
    </div>
  );
}
