from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any


RECOMMENDED_MODEL_MODES: dict[str, dict[str, str]] = {
    'best_video': {
        'label': 'Veo 3.1',
        'description': 'Best for cinematic short-form video.',
        'internal_model_key': 'veo3',
        'display_group': 'Best for Video',
    },
    'best_photos': {
        'label': 'GPT Image 1.5',
        'description': 'Best for realistic images and prompt fidelity.',
        'internal_model_key': 'openai_image',
        'display_group': 'Best for Photos & Realistic Images',
    },
    'best_graphics': {
        'label': 'Recraft',
        'description': 'Best for graphics, vector-style designs, and carousel assets.',
        'internal_model_key': 'recraft_studio',
        'display_group': 'Best for Graphics & Carousels',
    },
}

LEGACY_TEMPLATE_TO_HERO: dict[str, str] = {
    'explainer-video': 'character_explainer_reel',
    'history': 'historical_character_explainer',
    'mythology': 'character_explainer_reel',
    'music-video': 'viral_dance_clip',
    'character-vlog': 'character_explainer_reel',
    'storyboard': 'story_slides_reel',
    'product': 'client_ad_reel',
    'startup': 'client_ad_reel',
    'real-estate': 'client_ad_reel',
    'asmr-video': 'story_slides_reel',
    'cinematic_infographic': 'cinematic_infographic',
    'did_you_know': 'quote_infographic_post',
    'top_5_places': 'linkedin_carousel_pack',
    'history_timeline': 'linkedin_carousel_pack',
    'ecom-marble': 'product_ad_creative',
    'fashion-studio': 'product_ad_creative',
    'thumbnail-bg': 'thumbnail_cover_art',
    'podcast-cover': 'thumbnail_cover_art',
    'character-concept': 'product_ad_creative',
    'world-landscape': 'quote_infographic_post',
}


@dataclass(frozen=True)
class HeroTemplateSeed:
    id: str
    type: str
    category: str
    subcategory: str
    name: str
    slug: str
    description: str
    short_description: str
    thumbnail_url: str
    preview_image_url: str
    visual_prompt: str
    aspect_ratio: str
    inputs: list[dict[str, Any]]
    script_hint: str
    topic_hint: str
    prompt_template: str
    badge: str
    is_featured: bool
    is_quick_start: bool
    default_model_mode: str
    prompt_assembler_key: str
    legacy_mappings: list[str]
    suggested_platforms: list[str]
    suggested_durations: list[int]
    suggested_styles: list[str]
    safety_profile: str
    generation_defaults: dict[str, Any]

    def to_document(self, now: datetime) -> dict[str, Any]:
        mode = RECOMMENDED_MODEL_MODES[self.default_model_mode]
        return {
            'id': self.id,
            'type': self.type,
            'category': self.category,
            'subcategory': self.subcategory,
            'name': self.name,
            'title': self.name,
            'medium': self.type,
            'slug': self.slug,
            'description': self.description,
            'short_description': self.short_description,
            'thumbnail_url': self.thumbnail_url,
            'preview_image_url': self.preview_image_url,
            'visual_prompt': self.visual_prompt,
            'aspect_ratio': self.aspect_ratio,
            'inputs': self.inputs,
            'input_schema': self.inputs,
            'script_hint': self.script_hint,
            'topic_hint': self.topic_hint,
            'prompt_template': self.prompt_template,
            'active': True,
            'trending': True,
            'featured': self.is_featured,
            'order': 0,
            'created_by': 'system',
            'source': 'hero_registry',
            'badge': self.badge,
            'is_featured': self.is_featured,
            'is_quick_start': self.is_quick_start,
            'default_model_mode': self.default_model_mode,
            'prompt_assembler_key': self.prompt_assembler_key,
            'legacy_mappings': self.legacy_mappings,
            'suggested_platforms': self.suggested_platforms,
            'suggested_durations': self.suggested_durations,
            'suggested_styles': self.suggested_styles,
            'safety_profile': self.safety_profile,
            'recommended_model_name': mode['label'],
            'recommended_model_description': mode['description'],
            'recommended_model_group': mode['display_group'],
            'generation_defaults': self.generation_defaults,
            'created_at': now,
            'updated_at': now,
        }


HERO_TEMPLATE_REGISTRY: list[HeroTemplateSeed] = [
    HeroTemplateSeed(
        id='character_explainer_reel',
        type='video',
        category='Explainers',
        subcategory='character_explainer',
        name='Character Explainer Reel',
        slug='character-explainer-reel',
        description='Create educational or personality-led reels where a character explains a topic with strong social-first structure.',
        short_description='Historical, organ, mythology, or mascot explainers',
        thumbnail_url='https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
        preview_image_url='https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
        visual_prompt='Centered speaking character, cinematic framing, social-first vertical composition.',
        aspect_ratio='9:16',
        inputs=[
            {'key': 'speakerType', 'label': 'Speaker type', 'type': 'select', 'required': True, 'options': ['historical_figure', 'body_organ', 'mythology_character', 'mascot']},
            {'key': 'speakerName', 'label': 'Speaker name', 'type': 'text', 'required': True, 'placeholder': 'Ashoka / Heart / Hanuman / Brand Mascot'},
            {'key': 'topic', 'label': 'Topic', 'type': 'text', 'required': True, 'placeholder': 'How the heart pumps blood'},
            {'key': 'audience', 'label': 'Audience', 'type': 'text', 'required': False, 'placeholder': 'Students, parents, general audience'},
            {'key': 'tone', 'label': 'Tone', 'type': 'select', 'required': False, 'options': ['Educational', 'Inspiring', 'Dramatic', 'Friendly']},
            {'key': 'language', 'label': 'Language', 'type': 'select', 'required': True, 'options': ['English', 'Hindi', 'Hinglish']},
            {'key': 'platform', 'label': 'Platform', 'type': 'select', 'required': False, 'options': ['Instagram Reels', 'YouTube Shorts', 'LinkedIn']},
            {'key': 'duration', 'label': 'Duration', 'type': 'select', 'required': False, 'options': ['8', '12', '15']},
            {'key': 'visualStyle', 'label': 'Visual style', 'type': 'select', 'required': False, 'options': ['Cinematic', 'Cute Animated', 'Premium Explainer']},
            {'key': 'voiceStyle', 'label': 'Voice style', 'type': 'text', 'required': False, 'placeholder': 'Warm mentor, energetic educator'},
            {'key': 'textOverlay', 'label': 'Text overlay style', 'type': 'select', 'required': False, 'options': ['Minimal', 'Bold', 'Animated captions']},
            {'key': 'cta', 'label': 'CTA', 'type': 'text', 'required': False, 'placeholder': 'Follow for more explainers'},
        ],
        script_hint='Answer a few questions. We will build a full short-form explainer script with hook, scenes, and CTA.',
        topic_hint='Social-first character explainer reel',
        prompt_template='Create a {platform} reel where {speakerName} explains {topic} for {audience} in {language}. Tone: {tone}. Style: {visualStyle}. CTA: {cta}.',
        badge='Explainer',
        is_featured=True,
        is_quick_start=False,
        default_model_mode='best_video',
        prompt_assembler_key='character_explainer_reel',
        legacy_mappings=['explainer-video', 'history', 'mythology', 'character-vlog'],
        suggested_platforms=['Instagram Reels', 'YouTube Shorts', 'LinkedIn'],
        suggested_durations=[8, 12, 15],
        suggested_styles=['Cinematic', 'Cute Animated', 'Premium Explainer'],
        safety_profile='educational_character_safe',
        generation_defaults={'model_key': 'veo3', 'aspect_ratio': '9:16', 'resolution': '720p', 'voice': 'Shubh', 'language': 'English', 'duration_seconds': 12, 'quality': 'standard'},
    ),
    HeroTemplateSeed(
        id='viral_dance_clip',
        type='video',
        category='Social Viral',
        subcategory='dance_clip',
        name='Viral Dance Clip',
        slug='viral-dance-clip',
        description='Create loop-friendly, social-first dance clips designed for cute, shareable, high-retention content.',
        short_description='Baby, pet, or mascot dance moments',
        thumbnail_url='https://images.unsplash.com/photo-1516307365426-bea591f05011?auto=format&fit=crop&w=1200&q=80',
        preview_image_url='https://images.unsplash.com/photo-1516307365426-bea591f05011?auto=format&fit=crop&w=1200&q=80',
        visual_prompt='Cute energetic subject, clean background, vertical dance framing.',
        aspect_ratio='9:16',
        inputs=[
            {'key': 'subjectType', 'label': 'Subject type', 'type': 'select', 'required': True, 'options': ['baby_dance', 'pet_dance', 'mascot_dance']},
            {'key': 'subjectName', 'label': 'Subject name', 'type': 'text', 'required': False, 'placeholder': 'Golden retriever / baby Aarav / panda mascot'},
            {'key': 'danceStyle', 'label': 'Dance style', 'type': 'text', 'required': True, 'placeholder': 'Bhangra, freestyle, playful groove'},
            {'key': 'musicMood', 'label': 'Music mood', 'type': 'select', 'required': False, 'options': ['Upbeat', 'Cute', 'Funky', 'Festival']},
            {'key': 'outfitStyle', 'label': 'Outfit style', 'type': 'text', 'required': False, 'placeholder': 'Festival outfit, streetwear, mascot costume'},
            {'key': 'backgroundTheme', 'label': 'Background theme', 'type': 'text', 'required': False, 'placeholder': 'Neon stage, cozy room, Holi backdrop'},
            {'key': 'platform', 'label': 'Platform', 'type': 'select', 'required': False, 'options': ['Instagram Reels', 'YouTube Shorts']},
            {'key': 'duration', 'label': 'Duration', 'type': 'select', 'required': False, 'options': ['6', '8', '10']},
            {'key': 'loopPreference', 'label': 'Loop preference', 'type': 'select', 'required': False, 'options': ['Seamless loop', 'Strong final pose', 'Beat drop ending']},
        ],
        script_hint='No prompt engineering needed. We will assemble a loop-friendly dance brief with subject, movement, mood, and safe framing.',
        topic_hint='Cute, family-safe dance clip',
        prompt_template='Create a viral dance clip with {subjectName} performing {danceStyle}. Mood: {musicMood}. Background: {backgroundTheme}.',
        badge='Viral',
        is_featured=True,
        is_quick_start=False,
        default_model_mode='best_video',
        prompt_assembler_key='viral_dance_clip',
        legacy_mappings=['music-video'],
        suggested_platforms=['Instagram Reels', 'YouTube Shorts'],
        suggested_durations=[6, 8, 10],
        suggested_styles=['Cute', 'Festival', 'High-energy'],
        safety_profile='family_safe_social',
        generation_defaults={'model_key': 'veo3', 'aspect_ratio': '9:16', 'resolution': '720p', 'voice': 'Shubh', 'language': 'English', 'duration_seconds': 8, 'quality': 'standard'},
    ),
    HeroTemplateSeed(
        id='client_ad_reel',
        type='video',
        category='Ads & Promos',
        subcategory='ad_reel',
        name='Client Ad Reel',
        slug='client-ad-reel',
        description='Create polished short-form ads for products, services, real estate, or app launches with strong brand-safe structure.',
        short_description='Commercial-ready ad reel generator',
        thumbnail_url='https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1200&q=80',
        preview_image_url='https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1200&q=80',
        visual_prompt='Premium ad visuals, product or service hero moment, polished branded tone.',
        aspect_ratio='9:16',
        inputs=[
            {'key': 'businessType', 'label': 'Business type', 'type': 'select', 'required': True, 'options': ['product_ad', 'service_ad', 'real_estate_ad', 'app_promo']},
            {'key': 'productOrService', 'label': 'Product or service', 'type': 'text', 'required': True, 'placeholder': 'Luxury skincare line'},
            {'key': 'targetAudience', 'label': 'Target audience', 'type': 'text', 'required': True, 'placeholder': 'Young professionals in metro cities'},
            {'key': 'offer', 'label': 'Offer', 'type': 'text', 'required': False, 'placeholder': '15% launch discount'},
            {'key': 'tone', 'label': 'Tone', 'type': 'select', 'required': False, 'options': ['Premium', 'Urgent', 'Trust-building', 'Modern']},
            {'key': 'platform', 'label': 'Platform', 'type': 'select', 'required': False, 'options': ['Instagram Reels', 'YouTube Shorts', 'Facebook Ads']},
            {'key': 'duration', 'label': 'Duration', 'type': 'select', 'required': False, 'options': ['8', '12', '15']},
            {'key': 'brandColors', 'label': 'Brand colors', 'type': 'text', 'required': False, 'placeholder': 'Emerald green and matte gold'},
            {'key': 'headline', 'label': 'Headline', 'type': 'text', 'required': False, 'placeholder': 'Upgrade your glow routine'},
            {'key': 'cta', 'label': 'CTA', 'type': 'text', 'required': False, 'placeholder': 'Shop now / Book a visit / Download today'},
        ],
        script_hint='Tell us the offer and audience. We will build the ad hook, value delivery, and CTA automatically.',
        topic_hint='Brand-safe conversion-focused ad reel',
        prompt_template='Create a short ad reel for {productOrService} targeting {targetAudience}. Offer: {offer}. Tone: {tone}. CTA: {cta}.',
        badge='Ad Ready',
        is_featured=True,
        is_quick_start=False,
        default_model_mode='best_video',
        prompt_assembler_key='client_ad_reel',
        legacy_mappings=['product', 'startup', 'real-estate'],
        suggested_platforms=['Instagram Reels', 'YouTube Shorts', 'Facebook Ads'],
        suggested_durations=[8, 12, 15],
        suggested_styles=['Premium', 'Modern', 'Trust-building'],
        safety_profile='brand_safe_ad',
        generation_defaults={'model_key': 'veo3', 'aspect_ratio': '9:16', 'resolution': '720p', 'voice': 'Shubh', 'language': 'English', 'duration_seconds': 12, 'quality': 'standard'},
    ),
    HeroTemplateSeed(
        id='story_slides_reel',
        type='video',
        category='Explainers',
        subcategory='story_slides',
        name='Story Slides Reel',
        slug='story-slides-reel',
        description='Generate slide-based reels for listicles, timelines, before-after concepts, and compact mini-stories.',
        short_description='Top 5, timeline, before-after, and mini-story reels',
        thumbnail_url='https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80',
        preview_image_url='https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80',
        visual_prompt='Slide-led reel with strong transitions and text overlays.',
        aspect_ratio='9:16',
        inputs=[
            {'key': 'subtype', 'label': 'Format', 'type': 'select', 'required': True, 'options': ['top_5', 'timeline', 'before_after', 'mini_story']},
            {'key': 'topic', 'label': 'Topic', 'type': 'text', 'required': True, 'placeholder': 'Top 5 habits of high-performing creators'},
            {'key': 'audience', 'label': 'Audience', 'type': 'text', 'required': False, 'placeholder': 'Students, founders, creators'},
            {'key': 'tone', 'label': 'Tone', 'type': 'select', 'required': False, 'options': ['Energetic', 'Educational', 'Documentary', 'Premium']},
            {'key': 'platform', 'label': 'Platform', 'type': 'select', 'required': False, 'options': ['Instagram Reels', 'YouTube Shorts', 'LinkedIn']},
            {'key': 'duration', 'label': 'Duration', 'type': 'select', 'required': False, 'options': ['8', '12', '15']},
            {'key': 'cta', 'label': 'CTA', 'type': 'text', 'required': False, 'placeholder': 'Follow for more'},
        ],
        script_hint='We will turn your topic into a hook, slide flow, on-screen text plan, and ending CTA.',
        topic_hint='Slide-based short-form storytelling',
        prompt_template='Create a slide reel about {topic} using the {subtype} format. Tone: {tone}. CTA: {cta}.',
        badge='Slides',
        is_featured=True,
        is_quick_start=False,
        default_model_mode='best_video',
        prompt_assembler_key='story_slides_reel',
        legacy_mappings=['storyboard', 'asmr-video'],
        suggested_platforms=['Instagram Reels', 'YouTube Shorts', 'LinkedIn'],
        suggested_durations=[8, 12, 15],
        suggested_styles=['Energetic', 'Educational', 'Premium'],
        safety_profile='general_educational',
        generation_defaults={'model_key': 'veo3', 'aspect_ratio': '9:16', 'resolution': '720p', 'voice': 'Shubh', 'language': 'English', 'duration_seconds': 10, 'quality': 'standard'},
    ),
    HeroTemplateSeed(
        id='linkedin_carousel_pack',
        type='image',
        category='Carousels & Posts',
        subcategory='carousel_pack',
        name='LinkedIn Carousel Pack',
        slug='linkedin-carousel-pack',
        description='Create structured visual carousel covers and slide visuals for frameworks, comparisons, timelines, myth-busting, and stats posts.',
        short_description='Frameworks, comparisons, timelines, and myth-busting',
        thumbnail_url='https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1200&q=80',
        preview_image_url='https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1200&q=80',
        visual_prompt='Professional carousel cover, clean layout logic, strong visual hierarchy.',
        aspect_ratio='4:5',
        inputs=[
            {'key': 'carouselType', 'label': 'Carousel type', 'type': 'select', 'required': True, 'options': ['framework', 'comparison', 'timeline', 'myth_busting', 'stats']},
            {'key': 'topic', 'label': 'Topic', 'type': 'text', 'required': True, 'placeholder': '5-step hiring framework'},
            {'key': 'targetAudience', 'label': 'Target audience', 'type': 'text', 'required': False, 'placeholder': 'Founders and HR leaders'},
            {'key': 'brandName', 'label': 'Brand name', 'type': 'text', 'required': False, 'placeholder': 'RangManch AI'},
            {'key': 'tone', 'label': 'Tone', 'type': 'select', 'required': False, 'options': ['Professional', 'Bold', 'Minimal', 'Founder-led']},
            {'key': 'colorStyle', 'label': 'Color style', 'type': 'text', 'required': False, 'placeholder': 'Navy, ivory, and emerald'},
            {'key': 'slideCount', 'label': 'Slide count', 'type': 'select', 'required': False, 'options': ['5', '7', '10']},
            {'key': 'includeCTA', 'label': 'Include CTA', 'type': 'select', 'required': False, 'options': ['Yes', 'No']},
            {'key': 'includeLogo', 'label': 'Include logo', 'type': 'select', 'required': False, 'options': ['Yes', 'No']},
        ],
        script_hint='We will structure the core positioning and design direction so the carousel feels polished and shareable.',
        topic_hint='Professional carousel design system',
        prompt_template='Create a premium LinkedIn carousel cover about {topic} for {targetAudience}. Format: {carouselType}. Tone: {tone}.',
        badge='Carousel',
        is_featured=True,
        is_quick_start=False,
        default_model_mode='best_graphics',
        prompt_assembler_key='linkedin_carousel_pack',
        legacy_mappings=['top_5_places', 'history_timeline'],
        suggested_platforms=['LinkedIn', 'Instagram Carousel'],
        suggested_durations=[],
        suggested_styles=['Professional', 'Bold', 'Minimal'],
        safety_profile='professional_information',
        generation_defaults={'model_key': 'recraft_studio', 'aspect_ratio': '4:5', 'resolution': '1536'},
    ),
    HeroTemplateSeed(
        id='product_ad_creative',
        type='image',
        category='Ads & Promos',
        subcategory='product_ad_creative',
        name='Product Ad Creative',
        slug='product-ad-creative',
        description='Build polished performance creatives for e-commerce, luxury products, app promo visuals, and real estate posters.',
        short_description='Luxury product shots, app promos, and property posters',
        thumbnail_url='https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=1200&q=80',
        preview_image_url='https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=1200&q=80',
        visual_prompt='High-end commercial composition, polished product framing, conversion intent.',
        aspect_ratio='4:5',
        inputs=[
            {'key': 'productType', 'label': 'Product type', 'type': 'select', 'required': True, 'options': ['luxury_product', 'ecommerce_offer', 'app_promo_image', 'real_estate_poster']},
            {'key': 'productName', 'label': 'Product name', 'type': 'text', 'required': True, 'placeholder': 'Ayurvedic glow serum'},
            {'key': 'heroAngle', 'label': 'Hero angle', 'type': 'text', 'required': False, 'placeholder': 'Close-up bottle hero shot with soft reflections'},
            {'key': 'mood', 'label': 'Mood', 'type': 'select', 'required': False, 'options': ['Luxury', 'Modern', 'Urgent Offer', 'Trustworthy']},
            {'key': 'platform', 'label': 'Platform', 'type': 'select', 'required': False, 'options': ['Instagram', 'Meta Ads', 'Website']},
            {'key': 'colorPalette', 'label': 'Color palette', 'type': 'text', 'required': False, 'placeholder': 'Emerald and matte gold'},
            {'key': 'headline', 'label': 'Headline', 'type': 'text', 'required': False, 'placeholder': 'Glow, simplified'},
            {'key': 'logo', 'label': 'Logo text', 'type': 'text', 'required': False, 'placeholder': 'Brand mark or company name'},
            {'key': 'referenceImage', 'label': 'Reference direction', 'type': 'text', 'required': False, 'placeholder': 'Minimal studio product ad'},
        ],
        script_hint='We will build a commercial-grade ad prompt automatically so the output feels polished and ready for campaigns.',
        topic_hint='Performance ad creative',
        prompt_template='Create a product ad image for {productName}. Mood: {mood}. Headline: {headline}. Palette: {colorPalette}.',
        badge='Ad Ready',
        is_featured=True,
        is_quick_start=False,
        default_model_mode='best_photos',
        prompt_assembler_key='product_ad_creative',
        legacy_mappings=['ecom-marble', 'fashion-studio', 'character-concept'],
        suggested_platforms=['Instagram', 'Meta Ads', 'Website'],
        suggested_durations=[],
        suggested_styles=['Luxury', 'Modern', 'Trustworthy'],
        safety_profile='brand_safe_ad',
        generation_defaults={'model_key': 'openai_image', 'aspect_ratio': '4:5', 'resolution': '1536'},
    ),
    HeroTemplateSeed(
        id='quote_infographic_post',
        type='image',
        category='Carousels & Posts',
        subcategory='quote_infographic',
        name='Quote Infographic Post',
        slug='quote-infographic-post',
        description='Create shareable educational and insight-led post visuals for stats, quotes, and “did you know” content.',
        short_description='Stats cards, founder quotes, and educational posts',
        thumbnail_url='https://images.unsplash.com/photo-1526379095098-d400fd0bf935?auto=format&fit=crop&w=1200&q=80',
        preview_image_url='https://images.unsplash.com/photo-1526379095098-d400fd0bf935?auto=format&fit=crop&w=1200&q=80',
        visual_prompt='Clean educational social graphic, quote or stat anchored with one strong visual motif.',
        aspect_ratio='4:5',
        inputs=[
            {'key': 'postType', 'label': 'Post type', 'type': 'select', 'required': True, 'options': ['did_you_know', 'stats_card', 'founder_quote', 'educational_card']},
            {'key': 'topic', 'label': 'Topic', 'type': 'text', 'required': True, 'placeholder': 'Why the brain uses so much energy'},
            {'key': 'headline', 'label': 'Headline', 'type': 'text', 'required': False, 'placeholder': 'Did you know?'},
            {'key': 'tone', 'label': 'Tone', 'type': 'select', 'required': False, 'options': ['Educational', 'Bold', 'Founder-led', 'Minimal']},
            {'key': 'platform', 'label': 'Platform', 'type': 'select', 'required': False, 'options': ['Instagram', 'LinkedIn', 'X']},
            {'key': 'colorStyle', 'label': 'Color style', 'type': 'text', 'required': False, 'placeholder': 'Deep navy and warm gold'},
        ],
        script_hint='We will turn your raw topic into a polished shareable graphic direction, not just a basic prompt.',
        topic_hint='Insight-led social post',
        prompt_template='Create a premium post visual about {topic}. Format: {postType}. Tone: {tone}.',
        badge='Post',
        is_featured=True,
        is_quick_start=False,
        default_model_mode='best_graphics',
        prompt_assembler_key='quote_infographic_post',
        legacy_mappings=['did_you_know', 'world-landscape'],
        suggested_platforms=['Instagram', 'LinkedIn', 'X'],
        suggested_durations=[],
        suggested_styles=['Educational', 'Bold', 'Minimal'],
        safety_profile='educational_safe',
        generation_defaults={'model_key': 'recraft_studio', 'aspect_ratio': '4:5', 'resolution': '1536'},
    ),
    HeroTemplateSeed(
        id='thumbnail_cover_art',
        type='image',
        category='Covers & Thumbnails',
        subcategory='cover_art',
        name='Thumbnail Cover Art',
        slug='thumbnail-cover-art',
        description='Generate high-contrast cover art for YouTube, podcast, webinar, or launch thumbnails with strong hook composition.',
        short_description='YouTube thumbnails, podcast covers, webinar covers',
        thumbnail_url='https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80',
        preview_image_url='https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80',
        visual_prompt='Bold cover art, clean focal zone, high-contrast typography-safe composition.',
        aspect_ratio='16:9',
        inputs=[
            {'key': 'coverType', 'label': 'Cover type', 'type': 'select', 'required': True, 'options': ['youtube_thumbnail', 'podcast_cover', 'webinar_cover']},
            {'key': 'topic', 'label': 'Topic', 'type': 'text', 'required': True, 'placeholder': 'How creators go viral in 2026'},
            {'key': 'headline', 'label': 'Headline', 'type': 'text', 'required': False, 'placeholder': 'Go Viral Faster'},
            {'key': 'tone', 'label': 'Tone', 'type': 'select', 'required': False, 'options': ['Dramatic', 'Premium', 'Bold', 'Minimal']},
            {'key': 'platform', 'label': 'Platform', 'type': 'select', 'required': False, 'options': ['YouTube', 'Spotify', 'Webinar Landing Page']},
            {'key': 'colorStyle', 'label': 'Color style', 'type': 'text', 'required': False, 'placeholder': 'Dark navy with electric cyan accents'},
        ],
        script_hint='We will shape the composition and hook so the visual reads instantly at thumbnail size.',
        topic_hint='Hook-first cover art',
        prompt_template='Create cover art about {topic}. Headline: {headline}. Tone: {tone}.',
        badge='Cover',
        is_featured=True,
        is_quick_start=False,
        default_model_mode='best_photos',
        prompt_assembler_key='thumbnail_cover_art',
        legacy_mappings=['thumbnail-bg', 'podcast-cover'],
        suggested_platforms=['YouTube', 'Spotify', 'Webinar Landing Page'],
        suggested_durations=[],
        suggested_styles=['Dramatic', 'Premium', 'Bold'],
        safety_profile='general_marketing_safe',
        generation_defaults={'model_key': 'openai_image', 'aspect_ratio': '16:9', 'resolution': '1536'},
    ),
]


def get_hero_template_documents(now: datetime) -> list[dict[str, Any]]:
    return [item.to_document(now) for item in HERO_TEMPLATE_REGISTRY]


def get_recommended_model_mode(mode: str | None) -> dict[str, str] | None:
    if not mode:
        return None
    return RECOMMENDED_MODEL_MODES.get(mode)


def resolve_legacy_template_mapping(template_id: str) -> str | None:
    return LEGACY_TEMPLATE_TO_HERO.get(template_id)
