"""
Storyboard generation service.

Uses Gemini Flash to break down a clean script into detailed visual scene cards.
Independent from scene_planner.py - direct Gemini approach for duration-first design.
"""
from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass
from typing import Any

from app.core.config import get_settings
from app.providers.gemini import get_gemini_client
from app.recipes.storyboard_video import AdCategory, DURATION_RULES
from app.services.avatar_cultural_registry import (
    build_indian_urban_grounding_guidance,
    resolve_avatar_cultural_profile,
)

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class SceneCard:
    """Structured scene card generated by Gemini."""

    scene_number: int
    scene_type: str
    spoken_line: str
    visual_description: str
    shot_type: str
    avatar_action: str | None
    avatar_position: str | None
    environment: str | None
    mood: str
    product_visibility: str
    duration_seconds: int


class StoryboardGenerationService:
    """
    Generates detailed scene cards from a clean script using Gemini Flash.

    Duration-first approach:
    - Ideal: 20 seconds (4 scenes × 5 seconds each)
    - Max: 30 seconds (6 scenes × 5 seconds each)
    - Each scene gets default 5 seconds, can be overridden
    """

    def __init__(self) -> None:
        self.settings = get_settings()
        self.gemini = get_gemini_client()

    def generate_storyboard(
        self,
        *,
        clean_script: str,
        ad_category: str | AdCategory,
        avatar_description: str,
        avatar_id: str | None = None,
        avatar_name: str | None = None,
        business_context: str,
        platform: str,
        language: str = "en",
        tone: str = "casual",
    ) -> list[SceneCard]:
        """
        Generate detailed scene cards from a clean script.

        Args:
            clean_script: The approved script text to storyboard
            ad_category: One of 7 categories (e.g., "ugc_testimonial")
            avatar_description: Description of avatar/character (e.g., "young woman, natural makeup")
            business_context: Business brief (e.g., "skincare brand, focus on hydration benefits")
            platform: Target platform (e.g., "instagram_reels")
            language: Script language code (default: "en")
            tone: Tone of ad (default: "casual")

        Returns:
            List of SceneCard objects with visual descriptions, spoken lines, mood, etc.
        """
        if isinstance(ad_category, AdCategory):
            ad_category_str = ad_category.value
        else:
            ad_category_str = str(ad_category).lower()

        target_duration_seconds = self._extract_requested_duration_seconds(
            business_context=business_context,
            clean_script=clean_script,
        )
        estimated_script_seconds = round((len(clean_script.split()) / 150.0) * 60.0, 1)
        logger.info(
            "storyboard_scene_plan_target_duration",
            extra={"target_duration_seconds": target_duration_seconds},
        )
        logger.info(
            "storyboard_scene_plan_script_estimated_duration",
            extra={"script_estimated_duration_seconds": estimated_script_seconds},
        )
        logger.info(
            "storyboard_scene_plan_script_word_count",
            extra={"script_word_count": len(clean_script.split())},
        )
        ideal_scenes, max_scenes = self._resolve_scene_budget(target_duration_seconds)

        cultural_profile = resolve_avatar_cultural_profile(avatar_id=avatar_id, avatar_name=avatar_name)
        cultural_guidance = (
            build_indian_urban_grounding_guidance(cultural_profile)
            if cultural_profile and cultural_profile.nationality.lower() == "indian"
            else None
        )

        prompt = self._build_storyboard_prompt(
            clean_script=clean_script,
            ad_category=ad_category_str,
            avatar_description=avatar_description,
            business_context=business_context,
            platform=platform,
            language=language,
            tone=tone,
            ideal_scenes=ideal_scenes,
            max_scenes=max_scenes,
            cultural_guidance=cultural_guidance,
        )

        logger.info(
            "storyboard_generation_started",
            extra={
                "ad_category": ad_category_str,
                "script_length": len(clean_script),
                "ideal_scenes": ideal_scenes,
                "max_scenes": max_scenes,
                "platform": platform,
                "cultural_profile_applied": bool(cultural_guidance),
                "cultural_profile": (cultural_profile.cultural_profile if cultural_profile else None),
                "avatar_cultural_key": (cultural_profile.key if cultural_profile else None),
            },
        )

        try:
            response = self.gemini.generate_text(
                prompt,
                temperature=0.7,
                max_tokens=3000,
            )

            # Extract text from response dict
            if isinstance(response, dict):
                response_text = response.get("text", "")
            else:
                response_text = str(response)

            logger.info("storyboard_generation_raw_response", extra={
                "response_length": len(response_text),
                "response_preview": response_text[:200] if response_text else "EMPTY"
            })

            # Parse JSON response
            scene_cards = self._parse_scene_cards(response_text)
            scene_cards = self._enforce_scene_budget(
                scene_cards,
                target_duration_seconds=target_duration_seconds,
                max_scenes=max_scenes,
            )
            logger.info(
                "storyboard_generation_completed",
                extra={
                    "ad_category": ad_category_str,
                    "scene_count": len(scene_cards),
                    "total_duration": sum(s.duration_seconds for s in scene_cards),
                    "target_duration_seconds": target_duration_seconds,
                },
            )

            return scene_cards

        except Exception as e:
            logger.error(
                "storyboard_generation_failed",
                extra={
                    "ad_category": ad_category_str,
                    "error": str(e),
                },
            )
            raise RuntimeError(f"Failed to generate storyboard: {e}") from e

    def _extract_requested_duration_seconds(self, *, business_context: str, clean_script: str) -> int | None:
        def _extract(text: str) -> int | None:
            match = re.search(r"\b(\d{1,2})\s*(?:s|sec|secs|second|seconds)\b", text, flags=re.IGNORECASE)
            if not match:
                return None
            try:
                value = int(match.group(1))
            except ValueError:
                return None
            if value <= 0:
                return None
            return min(value, DURATION_RULES.max_duration_seconds)

        # Prefer explicit user brief duration over model-generated script text.
        context_value = _extract(business_context)
        if context_value is not None:
            return context_value
        return _extract(clean_script)

    def _resolve_scene_budget(self, target_duration_seconds: int | None) -> tuple[int, int]:
        if self.settings.storyboard_real_smoke_test_mode and not self.settings.storyboard_safe_test_mode:
            # Real-mode smoke test override: force compact storyboard for low-cost validation.
            return 2, 2
        if target_duration_seconds is None:
            max_scenes = int(DURATION_RULES.max_duration_seconds / DURATION_RULES.scene_duration_seconds)
            ideal_scenes = int(DURATION_RULES.ideal_duration_seconds / DURATION_RULES.scene_duration_seconds)
            return ideal_scenes, max_scenes
        if target_duration_seconds <= 6:
            return 2, 3
        if target_duration_seconds <= 10:
            return 2, 2
        if target_duration_seconds <= 15:
            return 3, 3
        if target_duration_seconds <= 20:
            return 4, 4
        if target_duration_seconds <= 30:
            return 5, 5
        max_scenes = int(DURATION_RULES.max_duration_seconds / DURATION_RULES.scene_duration_seconds)
        ideal_scenes = int(DURATION_RULES.ideal_duration_seconds / DURATION_RULES.scene_duration_seconds)
        return ideal_scenes, max_scenes

    def _enforce_scene_budget(
        self,
        scene_cards: list[SceneCard],
        *,
        target_duration_seconds: int | None,
        max_scenes: int,
    ) -> list[SceneCard]:
        trimmed = scene_cards[:max_scenes]
        if target_duration_seconds is None or not trimmed:
            return trimmed

        if self.settings.storyboard_real_smoke_test_mode and not self.settings.storyboard_safe_test_mode:
            # Real-mode smoke test override: enforce exactly 2 scenes totaling 5 seconds.
            enforced = trimmed[:2]
            if len(enforced) < 2:
                return enforced
            durations = [3, 2]
            normalized: list[SceneCard] = []
            for idx, (scene, dur) in enumerate(zip(enforced, durations), start=1):
                normalized.append(
                    SceneCard(
                        scene_number=idx,
                        scene_type=scene.scene_type,
                        spoken_line=scene.spoken_line,
                        visual_description=scene.visual_description,
                        shot_type=scene.shot_type,
                        avatar_action=scene.avatar_action,
                        avatar_position=scene.avatar_position,
                        environment=scene.environment,
                        mood=scene.mood,
                        product_visibility=scene.product_visibility,
                        duration_seconds=dur,
                    )
                )
            return normalized

        llm_total = sum(max(1, int(scene.duration_seconds or 0)) for scene in trimmed)
        logger.info(
            "storyboard_scene_duration_llm_total",
            extra={"target_duration_seconds": target_duration_seconds, "llm_total_duration_seconds": llm_total},
        )

        normalized_durations = self._normalize_scene_durations(
            scenes=trimmed,
            target_ad_duration_seconds=int(target_duration_seconds),
        )
        normalized: list[SceneCard] = []
        for idx, (scene, duration) in enumerate(zip(trimmed, normalized_durations), start=1):
            logger.info(
                "storyboard_scene_duration_original",
                extra={"scene_number": idx, "duration_seconds": int(scene.duration_seconds or 0)},
            )
            logger.info(
                "storyboard_scene_duration_normalized",
                extra={"scene_number": idx, "duration_seconds": int(duration)},
            )
            normalized.append(
                SceneCard(
                    scene_number=idx,
                    scene_type=scene.scene_type,
                    spoken_line=scene.spoken_line,
                    visual_description=scene.visual_description,
                    shot_type=scene.shot_type,
                    avatar_action=scene.avatar_action,
                    avatar_position=scene.avatar_position,
                    environment=scene.environment,
                    mood=scene.mood,
                    product_visibility=scene.product_visibility,
                    duration_seconds=int(duration),
                )
            )
        logger.info(
            "storyboard_scene_duration_total_after_normalization",
            extra={"target_duration_seconds": target_duration_seconds, "normalized_total_duration_seconds": sum(normalized_durations)},
        )
        return normalized

    def _normalize_scene_durations(self, *, scenes: list[SceneCard], target_ad_duration_seconds: int) -> list[int]:
        scene_count = max(1, len(scenes))
        target = int(target_ad_duration_seconds)

        exact_map: dict[tuple[int, int], list[int]] = {
            (10, 2): [5, 5],
            (15, 2): [7, 8],
            (15, 3): [5, 5, 5],
            (20, 2): [10, 10],
            (20, 4): [5, 5, 5, 5],
            (30, 4): [7, 8, 7, 8],
            (30, 5): [6, 6, 6, 6, 6],
        }
        if (target, scene_count) in exact_map:
            return exact_map[(target, scene_count)]

        min_scene = 3
        max_scene = 10
        weights = [max(1, len((scene.spoken_line or "").split())) for scene in scenes]
        total_weight = sum(weights) or scene_count

        raw = [max(min_scene, min(max_scene, int(round((w / total_weight) * target)))) for w in weights]
        current = sum(raw)
        idx = 0
        while current != target and scene_count > 0 and idx < 500:
            pointer = idx % scene_count
            if current < target and raw[pointer] < max_scene:
                raw[pointer] += 1
                current += 1
            elif current > target and raw[pointer] > min_scene:
                raw[pointer] -= 1
                current -= 1
            idx += 1

        if sum(raw) != target:
            base = target // scene_count
            remainder = target - (base * scene_count)
            raw = [base + (1 if i < remainder else 0) for i in range(scene_count)]
        return raw

    def _build_storyboard_prompt(
        self,
        *,
        clean_script: str,
        ad_category: str,
        avatar_description: str,
        business_context: str,
        platform: str,
        language: str,
        tone: str,
        ideal_scenes: int,
        max_scenes: int,
        cultural_guidance: str | None = None,
    ) -> str:
        """Build the Gemini prompt for scene generation."""
        category_instructions = self._category_scene_prompt_block(ad_category)
        cultural_block = ""
        if cultural_guidance:
            cultural_block = f"""
=== CULTURAL GROUNDING ===
{cultural_guidance}
- Bias environments, props, architecture, clothing, crowd demographics, and ambient styling toward premium Indian urban realism.
- Use Indian lifestyle photography aesthetic and regional realism tags such as Indian skin undertones, Indian facial diversity, and Indian urban architecture.
- Keep it subtle: no stereotypes, no forced ethnic costumes, no exaggerated cultural tropes.
"""
        return f"""You are an expert storyboard artist and director for short-form video ads.

Your task: Break down a script into detailed visual scene cards for a {ad_category} ad.

=== SCRIPT TO STORYBOARD ===
{clean_script}

=== CONTEXT ===
- Ad Category: {ad_category}
- Target Platform: {platform}
- Language: {language}
- Tone: {tone}
- Avatar/Character: {avatar_description if avatar_description and not avatar_description.startswith('av-') and len(avatar_description) < 30 else 'the creator avatar'}
- Business Context: {business_context}
{cultural_block}
=== CATEGORY-SPECIFIC CREATIVE RULES ===
{category_instructions}

=== DURATION CONSTRAINTS ===
- Create between {ideal_scenes} and {max_scenes} scenes.
- Each scene should be 3-10 seconds.
- Scene durations must add up to the requested target duration from context.
- For 10-second ads, create exactly 2 scenes of 5 seconds each.

=== SCENE CARD STRUCTURE ===
Each scene needs:
1. **scene_number**: 1, 2, 3, etc. (ordered sequentially)
2. **scene_type**: One of [hook_opening, problem_scene, solution_scene, feature_demo, testimonial, lifestyle, environmental, talking_head, close_up, wide_shot, transition]
3. **spoken_line**: Exact dialogue or VO text for this scene (can be empty for b-roll)
4. **visual_description**: Vivid, detailed description of what's on camera (setting, action, props, lighting style)
5. **shot_type**: One of [close_up, medium, wide, establishing, detail, product_focus]
6. **avatar_action**: What the avatar/character is doing (e.g., "applying cream", "looking at camera", "turning away", or None if no avatar)
7. **avatar_position**: Position in frame (e.g., "center", "left", "background", "off-screen", or None)
8. **environment**: Setting/location (e.g., "bathroom", "office", "sunny garden", or None if not relevant)
9. **mood**: Emotional tone of scene (e.g., "confident", "relieved", "curious", "excited", "vulnerable")
10. **product_visibility**: One of [prominent, subtle, implied, none]
11. **duration_seconds**: Scene duration (3-7 seconds, default 5)

=== QUALITY REQUIREMENTS ===
- Each scene should be visually distinct and forward the narrative
- Dialogue should be naturally broken across scenes, not all in one scene
- Match the specified {tone} tone throughout
- Ensure smooth visual transitions between scenes
- Product should be integrated naturally (not forced)
- Each scene should take ~5 seconds to perform/show

=== OUTPUT FORMAT ===
Return ONLY a valid JSON array of scene cards. Example:
[
  {{
    "scene_number": 1,
    "scene_type": "hook_opening",
    "spoken_line": "We all struggle with dry skin in winter",
    "visual_description": "Close-up of person's face, warm bathroom lighting, they're looking slightly down and to the side, thoughtful expression",
    "shot_type": "close_up",
    "avatar_action": "looking troubled",
    "avatar_position": "center",
    "environment": "bathroom",
    "mood": "concerned",
    "product_visibility": "none",
    "duration_seconds": 4
  }},
  ...
]

Generate the complete scene card array now:
"""

    def _category_scene_prompt_block(self, ad_category: str) -> str:
        key = str(ad_category or "").strip().lower()
        blocks: dict[str, str] = {
            "cinematic_narration": (
                "- Do NOT force a talking-head spokesperson.\n"
                "- Prioritize cinematic visual storytelling: product closeups, hand interactions, texture, environment, symbolic cutaways.\n"
                "- Spoken lines can be VO-first with minimal on-camera speaking.\n"
                "- Emphasize emotional arc and visual continuity over direct-to-camera delivery."
            ),
            "cinematic_broll": (
                "- Do NOT generate dialogue-heavy talking-head scenes.\n"
                "- Use micro visual beats and b-roll language: movement, atmosphere, details, transitions.\n"
                "- Keep spoken_line short or empty where visual-led storytelling is stronger.\n"
                "- Focus on product/material/environment continuity and cinematic pacing."
            ),
            "problem_solution": (
                "- Structure scene progression as: problem beat -> solution beat -> proof/benefit beat.\n"
                "- Product presence is optional unless provided, but solution clarity is mandatory.\n"
                "- Keep narrative practical and conversion-oriented."
            ),
            "founder_talking_head": (
                "- Human subject is expected and may speak directly to camera.\n"
                "- Keep framing and identity continuity stable across scenes."
            ),
            "ugc_testimonial": (
                "- Human subject/creator testimonial style is expected.\n"
                "- Use natural first-person delivery and authentic social tone."
            ),
            "inner_monologue": (
                "- Human subject is expected; delivery should feel introspective and personal.\n"
                "- Avoid loud promo phrasing; keep emotional continuity."
            ),
            "product_demo_lifestyle": (
                "- Balance human usage moments with product-focused visuals.\n"
                "- Ensure product continuity and practical usage demonstration."
            ),
        }
        return blocks.get(
            key,
            "- Keep category fit strong, narrative clear, and avoid forcing avatar-led talking head unless the category explicitly requires it.",
        )

    def _parse_scene_cards(self, response_text: str) -> list[SceneCard]:
        """Parse scene cards from Gemini response."""
        # Try to extract JSON from response
        json_str = response_text.strip()

        # If response is wrapped in markdown code blocks, extract it
        if "```json" in json_str:
            json_str = json_str.split("```json")[1].split("```")[0].strip()
        elif "```" in json_str:
            json_str = json_str.split("```")[1].split("```")[0].strip()

        try:
            data = json.loads(json_str)
        except json.JSONDecodeError as e:
            logger.error("storyboard_json_parse_failed", extra={"error": str(e), "response_preview": response_text[:500]})
            raise RuntimeError(f"Failed to parse Gemini response as JSON: {e}") from e

        if not isinstance(data, list):
            raise RuntimeError("Gemini response is not a list of scenes")

        scene_cards = []
        for item in data:
            try:
                scene = SceneCard(
                    scene_number=int(item.get("scene_number", 0)),
                    scene_type=str(item.get("scene_type", "")).strip(),
                    spoken_line=str(item.get("spoken_line", "")).strip(),
                    visual_description=str(item.get("visual_description", "")).strip(),
                    shot_type=str(item.get("shot_type", "medium")).strip(),
                    avatar_action=str(item.get("avatar_action") or "").strip() or None,
                    avatar_position=str(item.get("avatar_position") or "").strip() or None,
                    environment=str(item.get("environment") or "").strip() or None,
                    mood=str(item.get("mood", "neutral")).strip(),
                    product_visibility=str(item.get("product_visibility", "subtle")).strip(),
                    duration_seconds=int(item.get("duration_seconds", 5)),
                )
                scene_cards.append(scene)
            except Exception as e:
                logger.warning("storyboard_scene_parse_failed", extra={"item": item, "error": str(e)})
                continue

        if not scene_cards:
            raise RuntimeError("No valid scene cards could be parsed from Gemini response")

        return scene_cards
